### ISSUE TITLE
Plan for Sufia 7 work on HydraNorth

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1078]
- [ ] Dev deployment of Sufia 7
- [ ] Feature list for HydraNorth (derived from specs) for comparison with Sufia 7
- [ ] Identify functionality that will remain local HydraNorth work, and implement it with clean separation from Sufia, as a plugin
    - [ ] e.g. gem for admin functionality
    - [ ] theme
    - [ ] community / collection work
    - [ ] deposit form? We think we'll be able to use Sufia7 form
    - [ ] SAML
    - [ ] embargo

**Comment by weiweishi** [comment]
According to Project Hydra documentation, here are some guides for the migration:

https://github.com/projecthydra/sufia/wiki/Sufia-Management-Guide#migrating-data-to-pcdm-in-sufia-7

https://github.com/projecthydra/sufia/wiki/Sufia-6-to-Sufia-7-Migration

**Comment by pgwillia** [comment]
https://wiki.duraspace.org/display/hydra/Built-in+Feature+Checklist
