### ISSUE TITLE
Sufia7: Admin functions (note: is on roadmap for Sufia)

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1107]
- [ ] Users can’t delete
- [ ] Presentation of dashboard as faceted search results
- [ ] Actions for search results for admin (edit/delete)
