### ISSUE TITLE
Preservation Epic

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/HydraNorth#1251]
Short Term Activities
- [ ] Compare data streams for a few items from the HydraNorth repository with output from benchmark tools like Archivematica, ETDPlus etc.
 - A sample from Theses Deposit
 - A sample from current HydraNorth
 - A sample from PCDM based test repository
- [ ] Try running the Sufia out of the box audit feature on the same items and compare results
- [ ] Ingest a virus infected file into the repository and check the outcome
- [ ] Investigate items which failed characterization during ingest into the HydraNorth.
- [ ] Adjust settings, if needed, based on the above evaluations

Medium Term Activities
- [ ] Run Audit on all the objects in the repository and investigate items with failed result
- [ ] Try migrating a few sample files from Microsoft office 1997 to a recommended long-term preservation format

Long Term Activities
- [ ] A schema to capture premis, METS is not a must. Need a schema that can help to capture premis during ingest or can be generated based on already available content. We anticipate challenges with PCDM that we need to look at in the future.
- [ ] Need to work on how to create packages which are suited for our requirements both for access and preservation.

**Comment by pbinkley** [comment]
Merge into #258
