### ISSUE TITLE
Service migration from old ERA

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#257]
For production, this must include:

- [ ] migration of all ERA content #521
- [x] appropriate redirects #527
- [x] resolution of handles #528
- [x] users, permissions (CCID, Admin) #428
- [x] connect CCID-holding users with UAlberta permissions
- [x] HydraNorth config change #548 
- [x] historical usage data if possible #529
- [x] Reconfigure old ERA as thesis deposit interface #550

**Comment by pbinkley** [comment]
Issues:
- thesis - collections have unique metadata
- mapping of provenance
- CCID protection
- licensing info
- citation formats
Has to be ready for August final migration

User communication - Amanda

**Comment by pbinkley** [comment]
Discussion at product backlog grooming meeting June 12:
- license information: Mariana has been looking at info in ERA items, normalization across old ERA content (data entered in different fields, etc.) - working in OpenRefine - decisions regarding handling
- separation of license info from rights info
- problem: attached files - how to handle? extract text and paste into appropriate field? attach file as datastream? #422

**Comment by sfarnel** [comment]
we've been working to put in place the distinction between license and
rights which is definitely an enhancement over what we have been doing. as
well we're ensuring that every item has a rights and/or license statement
which we will also apply for other items in our collections which we
haven't been consistently doing.

On Fri, Jun 12, 2015 at 11:14 AM, Peter Binkley <notifications@github.com>
wrote:

> Discussion at product backlog grooming meeting June 12:
>
>    - license information: Mariana has been looking at info in ERA items,
>    normalization across old ERA content (data entered in different fields,
>    etc.) - working in OpenRefine - decisions regarding handling
>    - separation of license info from rights info
>    - problem: attached files - how to handle? extract text and paste into
>    appropriate field? attach file as datastream? #422
>    <https://github.com/ualbertalib/HydraNorth/issues/422>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/257#issuecomment-111561278>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
FYI. Google Analytic Data import now available. Still need a strategy to migrate the data over:
https://support.google.com/analytics/answer/3191589?hl=en

**Comment by pbinkley** [comment]
Further notes:

- After the migration, we want certains paths in current ERA to continue to work (e.g. the thesis deposit form). I think we can achieve this most easily by proxying these paths from new ERA to the old Tomcat site. But we need to test this to determine whether in proxying in the new environment creates any problems.
- If proxying doesn't work, we can mount old ERA at a new domain and just redirect from new ERA to old ERA for these paths.
- After the final migration, we don't want old content to be available on old ERA. We should delete all items except theses that are in progress (if any).
- FGSR will need access to the thesis workflow admin interface. This is just more paths that need to be proxied or redirected.
- We may want to modify the old ERA interface to remove navigational links from the header etc., reducing it to purely a thesis deposit site.

**Comment by pgwillia** [comment]
Discussed migrating theses coming out of embargo as items with a brief embargo so that the workflow which sends emails will be invoked #565

**Comment by weiweishi** [comment]
Failed migration will be captured by the audit #886
