### ISSUE TITLE
Fedora 4.2.0 upgrade

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#293]
(At this point we should look at [4.4](https://github.com/fcrepo4/fcrepo4/releases/tag/fcrepo-4.4.0))

New features:
- audit service (uses triple store)
- Fedora 3 to Fedora 4 migration - does this help us at all?

Done:
- [ ] Fedora 4.2 replaces Fedora 4.1, providing all current functionality
- [ ] Update Ansible playbook to install 4.2 (dev and production)
- [ ] Implement audit service of 4.2; document processes, including how to get reports.

**Comment by pbinkley** [comment]
This should come before other infrastructure work.

**Comment by pbinkley** [comment]
Parts:
- Spike - medium- timebox: 3 days
  - determine whether we can upgrade hydra-jetty for the community
  - determine effects of the triplestore requirement on our development environment
- integration into Ansible - medium
- integration into production - medium

**Comment by pbinkley** [comment]
This is subordinate to PCDM work #255

**Comment by pbinkley** [comment]
Replaced by #1034
