### ISSUE TITLE
Digitization epic

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#553]
- [ ] Metadata: MODS import
- [ ] PCDM
- [ ] Phasing: can we import single-file items under current Sufia generic-file model, and then migrate them to PCDM later? - this would allow us to do
  - Postcards (except multi-card booklets)
  - Magee
  - Maps (except multi-sheet items)
  - CIHM? - treat as metadata-only with link to old interface - apply this to all of current Peel? Newspapers?
  - Royal Commissions? serve as PDF?
  - Alberta Folklore and Local History?
- [ ] A/V - contract? (would require planning for metadata resources to match) - need to track Avalon work - perhaps run it separately from Hydra until we're ready to merge - will include collab with ITS to meet other A/V needs in the library
  - ability to store and preserve
  - ability to manage - workflows for metadata, derivatives (note: MOOCs are first target - [SCORM?](http://scorm.com/scorm-explained/technical-scorm/content-packaging/xml-schema-definition-files/) [LRMI?](http://dublincore.org/dcx/lrmi-terms/1.1/) [IEEE LOM?](https://standards.ieee.org/findstds/standard/1484.12.1-2002.html)) - check for updates on http://library.duke.edu/about/depts/repositoryservices/mooc-dams
  - ability to serve
  - ability to stream

**Comment by sfbetz** [comment]
Superseded by our roadmap. Can reopen if necessary.
