### ISSUE TITLE
Ingest updated Dataverse metadata (Feb 2016)

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#981]
We are using the occasion of preparing an ingest of updated Dataverse metadata into ERA as an opportunity to address several outstanding Dataverse issues.

If possible, we would like to coordinate the timing of the metadata harvesting with @wyman10 so that it captures several Dataverse studies that are close to being released.

Once these outstanding issues are resolved, we can proceed with the harvesting sequence.
- [x] #450 Dataverse object Deposit/modified time
- [x] #674 Author Order between Dataverse and HydraNorth
- [x] #951 Dataverse update should not create duplicates
- [x] #547 Add 'Abstract' to metadata display [resolved]

Harvesting sequence:
- [x] @wyman10 emails @johnhuck with confirmation that harvesting can begin.
- [x] @johnhuck creates ticket in Dataverse repo to request export
- [x] @piyapongch asks Henry to clear all files from the export destination folder(s) and then runs export job.
- [x] as required by outcome of #450, @johnhuck creates a ddi->dcterms stylesheet 
- [x] @johnhuck transforms exported metadata
- [x] @weiweishi runs script to ingest or update Dataverse objects in ERA.

Other Dataverse issues (open issues, but no dependencies for harvesting):
- #704 HTML Markup being displayed in dataverse metadata and collection pages
- #493 Dataverse to HydraNorth pt. 2: automation

**Comment by johnhuck** [comment]
After speaking with @sfarnel and @pbinkley, I have the understanding that the consensus is that we will attempt to capture the version dates from Dataverse for use as date uploaded and date modified in ERA, and so will prepare a new stylesheet to make dcterms metadata from the DDI.

**Comment by johnhuck** [comment]
@sfarnel @sfbetz @wyman10 @weiweishi 

I have finished work on the DDI to dcterms stylesheet, which generates the same metadata for ERA as the old stylesheet, just from a different source. I have made a couple of modifications, though, that I wanted to run by you first. Let me know if you have any objections.

The first mod is the addition of dcterms:dateSubmitted and dcterms:modified, which precipitated the work on a new stylesheet in the first place.

The second mod is that I have dropped the content that was coming over in a dc:relation element in the oai_dc metadata we were working with before. In ERA dcterms:relation has the label 'link to related item'. However, the values coming from Dataverse are drawn from three fields in the DDI that are meant for more free-form text: 'related studies,' 'other references,' and 'related material'. Leaving this information out avoids a jarring incongruity between a label that says 'link' and content that probably won't be a link most of the time. I think the information is better presented in the context of the full Dataverse record, which users can see by clicking through.

The third mod is that I have included the study subtitle, where one exists (a benefit of working with the richer DDI). This means longer titles in ERA (the title and subtitle are concatenated in the dcterms:title field and separated by a colon), but subtitles often include useful descriptive information. In addition, I have appended the version of the study in square brackets (e.g., '[Version 3]') to this longer title. I think it's important to include a version statement, so users will be be able to better interpret what the date modified means. It also draws attention to the fact that studies can be updated with new data: data that users, familiar with an earlier version, might want to check out.

If you have any concerns about these three modifications, do let me know. I will post a link to the stylesheet once I upload it to the metadata repo in case you want to take a look at it.

**Comment by johnhuck** [comment]
https://github.com/ualbertalib/metadata/blob/master/stylesheets/dataverse_DDI_to_ERA_dcterms.xsl

**Comment by johnhuck** [comment]
@weiweishi : I have transformed the Dataverse metadata and you can download it here:

https://drive.google.com/open?id=0B3s6m1gxi006flkta2JBSmkwVjc2Ti1kSXZHX2RmLVQyNjNjQkoweDFwQkNmMEhwSGg1OWs

The upload and modified dates should be self-evident in the XML. FYI, The root element has a different name now. You will notice that some items do not have a value for date created, and there is an empty element for those. If this causes a problem I can always rewrite the stylesheet, but I left it as-is, as I didn't think it would be a problem.

If you have any questions, just let me know.

**Comment by leahvanderjagt** [comment]
@johnhuck Is this ready for implementation? We are trying to decide whether to schedule this for sprint 39, and knowing how close this and all the other dataverse tickets you reference here are to 'done' will help us make that decision.

**Comment by johnhuck** [comment]
@leahvanderjagt yes, it is close. Weiwei has the files and so the ball is in her court now. She is also the one to advise about the other two open issues.

**Comment by leahvanderjagt** [comment]
OK, we will wait until she is back to evaluate. Thanks John.

On Thu, Mar 31, 2016 at 12:12 AM, johnhuck <notifications@github.com> wrote:

> @leahvanderjagt <https://github.com/leahvanderjagt> yes, it is close.
> Weiwei has the files and so the ball is in her court now. She is also the
> one to advise about the other two open issues.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/981#issuecomment-203771288>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pbinkley** [comment]
Update ran Apr. 22
